spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: "data-scraper"

  h2:
    console:
      enabled: true
  datasource:
    url: ${MYSQLDB_URL}
    username: ${MYSQLDB_USER}
    password: ${MYSQLDB_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_updates: true

website:
  url:
    scrape: "https://api.getro.com/api/v2/collections/89/search/jobs"
    api:
      job:
        functions: "https://api.getro.com/api/v2/collections/89/search/job_functions"
